apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx
  namespace: awx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awx
  template:
    metadata:
      labels:
        app: awx
    spec:
      containers:
      - name: awx
        image: quay.io/ansible/awx:23.5.0
        env:
        - name: SECRET_KEY
          value: awxsecretkey
        - name: DATABASE_USER
          value: awx
        - name: DATABASE_NAME
          value: awx
        - name: DATABASE_HOST
          value: awx-postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: awx-postgres-secret
              key: password
        - name: AWX_ADMIN_USER
          value: admin
        - name: AWX_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: awx-admin-password
              key: password
        ports:
        - containerPort: 8052
