apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: matter-server
spec:
  selector:
    app: matter-server
  ports:
    - protocol: TCP
      port: 5580
      targetPort: 5580
  type: ClusterIP
