---
- name: Deploy Updates
  hosts: all
  become: true
  tasks:
    - name: Deploy Updates - Red Hat
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Deploy Updates - Debian
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot requested by Ansible"
        pre_reboot_delay: 10
        post_reboot_delay: 30
        reboot_timeout: 600
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['needs_reboot'] or
            ansible_facts['os_family'] == "Debian" and ansible_facts['apt_reboot_required'] is defined and ansible_facts['apt_reboot_required']
      ignore_errors: yes