- name: Set timezone and configure NTP
  hosts: "*"
  become: true
  vars:
    ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') }}"
  tasks:
    - name: Set time zone to America/Chicago
      community.general.timezone:
        name: America/Chicago

    - name: Install chrony
      ansible.builtin.dnf:
        name: chrony
        state: present

    - name: Ensure chrony is running and enabled
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: true

    - name: Configure NTP servers, defaulting to Fedora Linux pool and restarts chrony
      ansible.builtin.blockinfile:
        path: /etc/chrony.conf
        block: |
          server 0.fedora.pool.ntp.org iburst
          server 1.fedora.pool.ntp.org iburst
          server 2.fedora.pool.ntp.org iburst
          server 3.fedora.pool.ntp.org iburst
      notify: Restart chrony

  handlers:
    - name: Restart chrony
      ansible.builtin.service:
        name: chronyd
        state: restarted
