- name: Update packages on all hosts
  hosts: "*"
  become: true
  vars:
    ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') }}"
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: present
