- hosts: "*"
  become: yes
  vars:
    ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') }}"
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest